### ISSUE TITLE
[Feature Request] Ability to search text

### ISSUE THREAD

**Issue by esmoak** [ATryder/TEdit#13]
Any chance a search function could be added to search text within a document? 

This is easily my favorite editor ever, and the only reason I have to keep another installed is to sometimes search for strings in long config files. 

Thanks for the awesome app.

**Comment by ATryder** [comment]
You're certainly welcome for the app, it's my favorite too, but I may have a slight bias.

It's been surprisingly cloudy lately, my setup is solar powered, and I've got a number of other things on my plate now and in the near future. This is quite doable though so I'm sure I'll be able to squeeze it in, but, you know, I don't really like to make promises so let's just say probably this year sometime :)

**Comment by ATryder** [comment]
A search and replace feature was added as of commit https://github.com/ATryder/TEdit/commit/0cc2e90b62ddf90ab85fc05ceb6ea18f3cbbb885

**Comment by esmoak** [comment]
Thank you. And best wishes to you.

**Comment by ATryder** [comment]
To you too my friend. I have a few more bits and bobs I'd like to squeeze in then I'll package up a v2.2 release.
