### ISSUE TITLE
App shows **unable to save ** while trying to save

### ISSUE THREAD

**Issue by julimaster** [ATryder/TEdit#5]
#### Expected behavior
After clicking on save icon ,my expectation was that app should save successfully.

#### Actual behavior
After clicking on save icon app was unable to save .

#### How to reproduce
1. Open the app
2. Click on the first icon which represent: create new documents
3. Then type ,after typing
4.  Then click on the 4th icon
5. Click on save it will bring unable to save

***
* Browser/App version:  TEdit version 2.1
* Operating system: Android marshmallow  6.0 ,tecno w3
***
#### Recording Of The Bug

![videotogif_2018.06.01_01.39.04.gif](https://cdn.steemitimages.com/DQmZ9QBKJ7DU7uPaEarcTC3B2nmACtoQqWqy6mwD2B4NeLD/videotogif_2018.06.01_01.39.04.gif)

**Comment by ATryder** [comment]
Open Android settings, select Apps-->TEdit-->Permissions and make sure the storage permission is enabled.

**Comment by ATryder** [comment]
See commit: https://github.com/ATryder/TEdit/commit/9cfd4c9dcb5074346147fa93eee2a94aaf8cf261
