### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by davidmind** [ATryder/TEdit#7]
Hi, @ATryder  am a graphics designer, i will like to know if you want me to create a new logo for your project. I will be creating it for free.

**Comment by Rudloff** [comment]
Hello,
I'm not sure why you are tagging me here, this is not my project :stuck_out_tongue:

**Comment by davidmind** [comment]
Ooh my bad i thought i tag @ATryder, i will edit it now. Sorry for that

**Comment by ATryder** [comment]
Sure go right ahead.

**Comment by davidmind** [comment]
Ok i will work on it and give you feed back ASAP.

**Comment by davidmind** [comment]
@ATryder sorry for the delay i was a little bit busy, ast week. After making different sketches, and considering the layout and functions of your project. I came up with this.
![text-editor-presentation](https://user-images.githubusercontent.com/37777956/42220661-850c5b1a-7ec7-11e8-8b02-20b6220cfd25.png)

**Comment by ATryder** [comment]
Cool, would it be possible to get that in svg format?

**Comment by davidmind** [comment]
Yes, i will submit a link to the editable file, while i also make a pull request based on your selected color for the logo icon.

**Comment by ATryder** [comment]
I like the green

**Comment by davidmind** [comment]
Ok i proceed to make a pull request and i will also submit a link for the editable files here, including **SVG**

**Comment by davidmind** [comment]
@ATryder which of the green launcher icon, should i submit as a pull request. The square, round shape, or both?

**Comment by davidmind** [comment]
@ATryder This is a link to editable and png file for both round and square green launcher icon. **[here](https://drive.google.com/folderview?id=16y-TLSHWMrUlTZaSHsJJ6LVwo5zjsLzx)**

**Comment by ATryder** [comment]
Both the square and round would be appreciated.

**Comment by davidmind** [comment]
Ok i will make pull request for both launcher icon

**Comment by davidmind** [comment]
@ATryder i have make a pull request

**Comment by ATryder** [comment]
The new icon is all setup. Thanks again, looks great!

**Comment by ATryder** [comment]
https://github.com/ATryder/TEdit/commit/4ad913a5b6a94489a44bbef2a20b494143215daa
