### ISSUE TITLE
Saves filename with .txt appended to it even if I explicitly remove it during naming 

### ISSUE THREAD

**Issue by RonerCodes** [ATryder/TEdit#8]
I  needed to create a text file as a configuration file for another app that doesn't use an extension.

**Comment by ATryder** [comment]
Issue resolved: https://github.com/ATryder/TEdit/commit/e1082972b25e0154a90f1af10a5b4df0fed98514

The above commit allows TEdit to save files without an extension. Additionally Android API level 26 added a mechanism for detecting MIME types using built-in detection mechanisms. For Android devices running Oreo, 8.0, and above TEdit will take advantage of this to filter supported file types. On my device this still does not detect text files without an extension, but these files can still be edited with TEdit by opening them with a file manager, such as OI Manager, and selecting TEdit from the list of available applications to open the file.
